version: '3.8'

services:
  app-consultas:
    container_name: consultas-camel-container
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: on-failure
